apiVersion: v2
name: ls-k8s-webadc
description: A Helm chart for LiteSpeed Web ADC Ingress Controller
type: application
version: 0.1.19
appVersion: "0.1.19"
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
icon: https://litespeedtech.com/images/icons/web-adc-logo-icon.png
